{% set version = '0.0.4' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-sparklyr.nested
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/sparklyr.nested_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/sparklyr.nested/sparklyr.nested_{{ version }}.tar.gz
  sha256: ecece96001c8c2acbe9dae2b68ac2dd166be038d2e92f06ce6cfa19200c1aca0

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-dplyr
    - r-jsonlite
    - r-listviewer
    - r-purrr
    - r-rlang
    - r-sparklyr
    - r-tidyselect
  run:
    - r-base
    - r-dplyr
    - r-jsonlite
    - r-listviewer
    - r-purrr
    - r-rlang
    - r-sparklyr
    - r-tidyselect

test:
  commands:
    - $R -e "library('sparklyr.nested')"           # [not win]
    - "\"%R%\" -e \"library('sparklyr.nested')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=sparklyr.nested
  license: Apache-2.0
  summary: A 'sparklyr' extension adding the capability to work easily with nested data.
  license_family: APACHE
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: sparklyr.nested
# Title: A 'sparklyr' Extension for Nested Data
# Version: 0.0.4
# Authors@R: c( person("Matt", "Pollock", email = "mpollock@mitre.org", role = c("aut", "cre")), person(family = "The MITRE Corporation", role = c("cph")) )
# Maintainer: Matt Pollock <mpollock@mitre.org>
# Description: A 'sparklyr' extension adding the capability to work easily with nested data.
# Depends: R (>= 3.3)
# Imports: sparklyr, jsonlite, listviewer, dplyr, rlang, purrr, tidyselect
# Suggests: testthat, reactR
# License: Apache License 2.0 | file LICENSE
# SystemRequirements: Spark: 1.6.x or 2.x
# Encoding: UTF-8
# RoxygenNote: 7.2.3
# BugReports: https://github.com/mitre/sparklyr.nested/issues
# NeedsCompilation: no
# Packaged: 2023-02-20 21:39:05 UTC; frodo
# Author: Matt Pollock [aut, cre], The MITRE Corporation [cph]
# Repository: CRAN
# Date/Publication: 2023-02-20 22:00:03 UTC
